ckeditor5.plugin.ckeditor5_fe_color:
  type: mapping
  label: Custom colors
  mapping:
    colors:
      type: sequence
      label: 'Colors'
      sequence:
        type: mapping
        label: 'Color'
        mapping:
          label:
            type: string
          color:
            type: string
          class:
            type: string
          options:
            type: mapping
            mapping:
              hasBorder:
                type: boolean
                label: 'Has border'
                default: false
